version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.10
      - test-3.9
      - test-3.8
      - test-3.7
jobs:
  test-3.6: &test-template
    working_directory: ~/not-na/peng3d
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      DISPLAY: :99
    # browsers variant is required because we need an X-Server
    docker:
      - image: cimg/python:3.6-browsers
    steps:
      # Machine Setup
      - checkout
      
      # Dependencies
      - run: sudo apt update
      - run:
          name: Install GLUT
          command: sudo apt install freeglut3-dev
      - run:
          name: Install pip dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox

      - run:
          name: Show installed packages
          command: |
            . venv/bin/activate
            pip freeze

      # Test
      - run:
          name: Run tests
          command: | 
            . venv/bin/activate
            python3 -m tox -- --junitxml=test-results/junit.xml --x-display=$DISPLAY -v -m "not graphical"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
  test-3.7:
    <<: *test-template
    docker:
      - image: cimg/python:3.7-browsers
  test-3.8:
    <<: *test-template
    docker:
      - image: cimg/python:3.8-browsers
  test-3.9:
    <<: *test-template
    docker:
      - image: cimg/python:3.9-browsers
  test-3.10:
    <<: *test-template
    docker:
      - image: cimg/python:3.10-browsers
